services:
  packsolver_api:
    image: packsolverapi:dev
    # container_name: PackSolverAPI
    environment:
      - ASPNETCORE_HTTP_PORTS=8081
    build:
      context: .
      dockerfile: "Dockerfile"
    ports:
      - "8081:8081"
  sql_server:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022
    ports:
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=Daniel321.
    volumes:
      - sql_data:/var/opt/mssql
volumes:
  sql_data: