// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PackSolverAPI.DbContexts;

#nullable disable

namespace PackSolverAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OrderProduct", b =>
                {
                    b.Property<int>("OrdersOrderId")
                        .HasColumnType("int");

                    b.Property<string>("ProductsProductId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("OrdersOrderId", "ProductsProductId");

                    b.HasIndex("ProductsProductId");

                    b.ToTable("OrderProduct");
                });

            modelBuilder.Entity("PackSolverAPI.Models.Box", b =>
                {
                    b.Property<string>("BoxId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<int>("Length")
                        .HasColumnType("int");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("BoxId");

                    b.ToTable("boxes");

                    b.HasData(
                        new
                        {
                            BoxId = "CAIXA_1",
                            Height = 30,
                            Length = 80,
                            Width = 40
                        },
                        new
                        {
                            BoxId = "CAIXA_2",
                            Height = 80,
                            Length = 40,
                            Width = 50
                        },
                        new
                        {
                            BoxId = "CAIXA_3",
                            Height = 50,
                            Length = 60,
                            Width = 80
                        });
                });

            modelBuilder.Entity("PackSolverAPI.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.HasKey("OrderId");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("PackSolverAPI.Models.Product", b =>
                {
                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<int>("Length")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("products");
                });

            modelBuilder.Entity("PackSolverAPI.Models.ProductBox", b =>
                {
                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BoxId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "BoxId");

                    b.HasIndex("BoxId");

                    b.HasIndex("OrderId");

                    b.ToTable("productBoxes");
                });

            modelBuilder.Entity("OrderProduct", b =>
                {
                    b.HasOne("PackSolverAPI.Models.Order", null)
                        .WithMany()
                        .HasForeignKey("OrdersOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PackSolverAPI.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PackSolverAPI.Models.ProductBox", b =>
                {
                    b.HasOne("PackSolverAPI.Models.Box", "Box")
                        .WithMany("productBoxes")
                        .HasForeignKey("BoxId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PackSolverAPI.Models.Order", "Order")
                        .WithMany("ProductBoxes")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PackSolverAPI.Models.Product", "Product")
                        .WithMany("productBoxes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Box");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PackSolverAPI.Models.Box", b =>
                {
                    b.Navigation("productBoxes");
                });

            modelBuilder.Entity("PackSolverAPI.Models.Order", b =>
                {
                    b.Navigation("ProductBoxes");
                });

            modelBuilder.Entity("PackSolverAPI.Models.Product", b =>
                {
                    b.Navigation("productBoxes");
                });
#pragma warning restore 612, 618
        }
    }
}
